apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service
  labels:
    app: book-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
        - name: book-service
          image: akashgajjala10/book-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql://akash_sit722_part2_user:0CBj7sq6BPtHZ2fR8u1VeGX48cr6w9AB@dpg-crcidbd2ng1s73csjcc0-a/akash_sit722_part2"
